### ISSUE TITLE
exit region

### ISSUE THREAD

**Issue by medrockstar** [lulibrary/Background-Beacon-Monitoring#1]
Hi,

is there on exit region ?

Tks,

**Comment by stephenrob** [comment]
The on exit event is handled in 

```
Background-Beacon-Monitoring/src/android/uk/ac/lancaster/library/backgroundbeacons/BeaconLoggingMonitorNotifier.java
```

This logs the exit event to the API server which is the aim of this.

We choose to wrap this into a cordova plugin so we can initialise the plugin within the cordova project and use it in multiple projects if needed.

Due to the application life cycle with cordova when the application is quit events cannot be fired back up to the javascript layer to be handled which why we made this to handle the events in the same way we would at the javascript/cordova layer but down at the actual OS level.
